"""empty message

Revision ID: 4bae51308dc4
Revises: 
Create Date: 2020-08-05 22:38:20.808590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bae51308dc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_city', sa.Text(), nullable=True))
    op.add_column('event', sa.Column('event_country', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_country')
    op.drop_column('event', 'event_city')
    # ### end Alembic commands ###
